name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag swisskiwi2004/rescueit-test:1.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: swisskiwi2004
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push Docker image
      run: docker push swisskiwi2004/rescueit-test:1.2


env:
    RESCUEITDBpassword: ${{ secrets.RESCUEITDB_PASS }}
    RESCUEITJWTsecret: ${{ secrets.RESCUEITJWTSECRET }}
