name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag swisskiwi2004/rescueit-test:latest

    - name: Push Docker image
      run: docker push swisskiwi2004/rescueit-test:latest
      env:
        DOCKER_USERNAME: yourusername
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

env:
    RESCUEITDBpassword: ${{ secrets.RESCUEITDB_PASS }}
